update yima_0 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_1 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_2 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_3 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_4 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_5 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_6 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_7 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_8 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_9 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_10 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_11 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_12 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_13 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_14 set user_address = '{}' where user_address = '' OR user_address is null;
update yima_15 set user_address = '{}' where user_address = '' OR user_address is null;
ALTER TABLE `yima_0` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_1` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_2` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_3` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_4` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_5` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_6` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_7` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_8` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_9` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_10` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_11` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_12` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_13` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_14` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';
ALTER TABLE `yima_15` CHANGE `user_address` `user_address`  JSON NOT NULL COMMENT '激活的用户地址 JSON';